config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'applications/index'

  root to: 'applications#index'

  resources :applications do
    resources :tests
    resources :answers
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :test
  belongs_to :application
  belongs_to :user
end

app/models/application.rb
class Application < ApplicationRecord
	belongs_to :user

	has_many :tests
	has_many :answers

	accepts_nested_attributes_for :tests, reject_if: :all_blank, allow_destroy: true

	validates :name, :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :application, required: false
  validates :question, presence: true
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applications
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		@application = Application.find(params[:application_id])
		@answer = @application.answers.create(params[:answer].permit(:reply))
		@answer.user_id = current_user.id if current_user
		@answer.save

		if @answer.save
			redirect_to application_path(@application)
		else
			render 'applications/new'
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
  	devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login, :email, :password, :remember_me) }
  	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
	before_action :find_application, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show	]

	def index
		@applications = Application.all.order("created_at DESC").limit(3)
	end

	def new	
	  @application = current_user.applications.build
	  @application.tests.build
	end

	def create
		@application = current_user.applications.build(application_params)

		if @application.save
			redirect_to @application
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @application.update(application_params)
			redirect_to @application
		else
			render 'edit'
		end
	end


	def destroy
		@application.destroy
		redirect_to root_path
	end

	private

	def find_application
		@application = Application.find(params[:id])
	end

	def application_params
		params.require(:application).permit(:name, :description, tests_attributes: [:id, :question, :_destroy])
	end

	def after_sign_out_path_for(resource_or_scope)
	redirect_to root_path
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/answers/_form.html.erb
<%= form_for([@application, @application.answers.build]) do |f| %>
	<div class="field">
		<%= f.text_field :reply %>
		<%= f.submit class: "btn btn-default" %>
	</div>
<% end %>

app/views/answers/_reply.html.erb
<div class"reply">
	<%= answers.reply %>
</div>

app/views/applications/_form.html.erb
<%= form_for @application, html: { multipart: true } do |f| %>
	<div class="field">
		<label for="title"><%= f.label :title %><br></label>
		<%= f.text_field :name, placeholder: "Name of Your Friend Test", class: "form-control" %><br>
		<label for="description"><%= f.label :description %><br></label>
		<%= f.text_field :description, placeholder: "Write a witty tagline for your test.", class: "form-control" %><br>
	</div>
	<h3>Questions</h3>
	<div id="questions">
		<%= f.fields_for :tests do |test| %>
			<%= render 'questions_fields', f: test %>
		<% end %>
		<div class="links">
			<%= link_to_add_association 'Add Question', f, :tests %>
		</div>
	</div>
	<div class="form-actions">
		<%= f.submit class: "btn btn-default" %>
	</div>
<% end %>

app/views/applications/_questions_fields.html.erb
<div class="nested-fields">
  <%= f.text_field :question, placeholder: "Ask something only a friend would know." %>
  <%= link_to_remove_association "Remove Question", f %>
</div>

app/views/applications/index.html.erb
<h1>This is a test to see if you really know your "friend".</h1>
<h5>We're tired of people saying they are friends but they really know nothing about each other. We're bringing some integrity back to "friends".</h5>
<h3>Pass the test and you get accepted. Fail the test and you get nothing.</h3>

<h2>My Tests</h2>
<% if user_signed_in? %>
	<%= link_to "New Friend Test", new_application_path %>
<% end %>
<div class="applications_index">
	<% @applications.each do |application| %>
		<ul>
			<li><b><%= link_to application.name, application %></b><br>
			<i><%= link_to application.description, application %></i></li>
	  </ul>
	<% end %>
</div>

app/views/applications/new.html.erb
<h1>New Friend Test</h1>
<% if user_signed_in? %>
	<%= form_for @application do |f| %>
		<% if @application.errors.any? %>
		  <div id="errors">
		    <p><%= @application.errors.count %> Prevented this application from saving</p>
		    <ul>
		      <% @application.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>
		<div class="field">
			<%= f.label :title %><br>
			<%= f.text_field :name, placeholder: "Name of Your Friend Test", class: "form-control" %><br>
			<%= f.label :description %><br>
			<%= f.text_field :description, placeholder: "Write a witty tagline for your test.", class: "form-control" %><br>
		</div>
		<h3>Questions</h3>
			<p>Add about 10-20 questions that only a friend would know.</p>
			<%= f.fields_for :tests do |test| %>
				<div id="questions">
					<div class="field">
				  	<%= render 'questions_fields', f: test %>
			  	 <div class="links">
				  	<%= link_to_add_association 'Add Question', f, :tests, partial: 'questions_fields' %>
				   </div>
				  </div>
				</div>
			<% end %>
		<br>
		<div class="form-actions">
			<%= f.button :submit %>
		</div>
	<% end %>
<% end %>

app/views/applications/show.html.erb
<h1><%= @application.name %></h1>
<h4><i><%= @application.description %></i></h4>
<h3>Questions</h3>
<ul>
	<% @application.tests.each do |test| %>
		<li>
			<%= test.question + "?" %>
		</li>
	<% end %>
</ul>

<h2><%= @application.answers.count %></h2>
<%= render @application.answers %>

<%= render 'answers/form' %>

<h6><%= link_to "Back", root_path %></h6>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friend App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="site_title">
    	<h1><%= link_to "Friend App", root_path %></h1>
    	<p>Are you <i>really</i> friends?</p>
    </div>
    <ul>
      <% if user_signed_in? %>
        <li><%= current_user.email %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to('Sign Up', new_user_registration_path) %></li>
        <li><%= link_to('Sign In', new_user_session_path) %></li>
      <% end %>
    </ul>

    <%= yield %>
  </body>
</html>